export const DEFAULT_WORKOUTS = [
    "Peito",
    "Costas",
    "Dorsal",
    "Lombar",
    "Ombros",
    "Deltoide anterior",
    "Deltoide lateral",
    "Deltoide posterior",
    "Trapézio",
    "Bíceps",
    "Tríceps",
    "Antebraço",
    "Abdômen",
    "Oblíquos",
    "Core",
    "Glúteos",
    "Quadríceps",
    "Posterior de coxa",
    "Adutores",
    "Abdutores",
    "Panturrilhas",
    "Tibial anterior",
    "Cardio",
    "Corpo inteiro",
    "Mobilidade",
    "Alongamento"
] as const;